name: CI

on:
  push:
  pull_request:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: test
      - run: make integration_test
  build:
    runs-on: ubuntu-latest
    needs:
      - integration_test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: public.ecr.aws/cookpad/itacho
          tags: |
            type=sha,format=long
            type=ref,event=tag
      - uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
